# Generated by Django 5.0.6 on 2024-07-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivoFijo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kace', models.IntegerField(blank=True, null=True, verbose_name='TicketKace')),
                ('categoria', models.CharField(max_length=255)),
                ('usuario_asignado', models.CharField(max_length=255)),
                ('usuario_anterior', models.CharField(max_length=255)),
                ('NoOrdenCompra', models.CharField(max_length=255)),
                ('NoResponsiva', models.CharField(max_length=255)),
                ('Sucursal', models.CharField(max_length=255)),
                ('NoSerie', models.CharField(max_length=255)),
                ('MarcaEquipo', models.CharField(max_length=255)),
                ('ModeloEquipo', models.CharField(max_length=255)),
                ('RAM', models.IntegerField(blank=True, null=True, verbose_name='RAM')),
                ('Almacenamiento', models.IntegerField(blank=True, null=True, verbose_name='Almacenamiento')),
                ('Category', models.CharField(max_length=255)),
                ('WorkSpace', models.CharField(max_length=255)),
                ('NoSerial', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Logeo',
        ),
    ]
